### PR TITLE
Fix build on Ubuntu 22.04 / 5.15 kernel

### PR DESCRIPTION
**Pull request by andriytk**
Fix build errors on Ubuntu 22.04 / linux kernel 5.15:

```
$ make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-25-generic/build M=/home/ant/rtl8812au  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-25-generic'
  CC [M]  /home/ant/rtl8812au/core/rtw_cmd.o
/home/ant/rtl8812au/core/rtw_cmd.c: In function ‘rtw_cmd_thread’:
/home/ant/rtl8812au/core/rtw_cmd.c:557:1: error: control reaches end of non-void function [-Werror=return-type]
  557 | }
      | ^
...
  CC [M]  /home/ant/rtl8812au/core/rtw_mp.o
/home/ant/rtl8812au/core/rtw_mp.c: In function ‘mp_xmit_packet_thread’:
/home/ant/rtl8812au/core/rtw_mp.c:1182:1: error: no return statement in function returning non-void [-Werror=return-type]
 1182 | }
      | ^
cc1: some warnings being treated as errors
```

And:

```
  LD [M]  /home/ant/rtl8812au/8812au.o
  MODPOST /home/ant/rtl8812au/Module.symvers
ERROR: modpost: "kthread_complete_and_exit" [/home/ant/rtl8812au/8812au.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:134: /home/ant/rtl8812au/Module.symvers] Error 1
```

### CODE REVIEW

**Comment by topherbuckley** [comment]
Bump!. This PR is much easier to read than Chinese for me! Found a similar workaround from one of the [issues](https://github.com/gnab/rtl8812au/issues/250), plus it handles old and new kernels.
